version: '3.8'

services:
  mariadb:
    image: mariadb:11.7.2
    container_name: korea-stock-mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MARIADB_DATABASE: stock_db
      MARIADB_USER: ${DB_USERNAME:-stock_user}
      MARIADB_PASSWORD: ${DB_PASSWORD:-password}
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/mariadb/init:/docker-entrypoint-initdb.d
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO
      --innodb-buffer-pool-size=1G
      --innodb-log-file-size=256M
      --max-connections=200
      --query-cache-size=64M
      --query-cache-type=1
    networks:
      - korea-stock-network

  redis:
    image: redis:7.2-alpine
    container_name: korea-stock-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-}
    networks:
      - korea-stock-network

  batch-collector:
    build:
      context: .
      dockerfile: ./docker/batch-collector/Dockerfile
    container_name: korea-stock-batch
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_USERNAME: ${DB_USERNAME:-stock_user}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      KIS_APP_KEY: ${KIS_APP_KEY}
      KIS_APP_SECRET: ${KIS_APP_SECRET}
      KIS_ENVIRONMENT: ${KIS_ENVIRONMENT:-real}
    depends_on:
      - mariadb
      - redis
    networks:
      - korea-stock-network

  api-server:
    build:
      context: .
      dockerfile: ./docker/api-server/Dockerfile
    container_name: korea-stock-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_USERNAME: ${DB_USERNAME:-stock_user}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
    depends_on:
      - mariadb
      - redis
    networks:
      - korea-stock-network

volumes:
  mariadb_data:
    driver: local
  redis_data:
    driver: local

networks:
  korea-stock-network:
    driver: bridge