CREATE TABLE `stock_information` (
  `short_code` varchar(20) NOT NULL COMMENT '단축코드',
  `standard_code` varchar(20) NOT NULL COMMENT '표준코드 (ISIN)',
  `korean_name` varchar(100) NOT NULL COMMENT '종목 한글명',
  `group_code` varchar(10) DEFAULT NULL COMMENT '그룹코드',
  `market_cap_scale` varchar(10) DEFAULT NULL COMMENT '시가총액 규모',
  `index_sector_major` varchar(50) DEFAULT NULL COMMENT '지수업종 대분류',
  `index_sector_middle` varchar(50) DEFAULT NULL COMMENT '지수업종 중분류',
  `index_sector_minor` varchar(50) DEFAULT NULL COMMENT '지수업종 소분류',
  `is_manufacturing` char(1) DEFAULT 'N' COMMENT '제조업 여부',
  `is_low_liquidity` char(1) DEFAULT 'N' COMMENT '저유동성 여부',
  `is_governance_index` char(1) DEFAULT 'N' COMMENT '지배구조지수 종목 여부',
  `kospi200_sector` varchar(50) DEFAULT NULL COMMENT 'KOSPI200 섹터업종',
  `is_kospi100` char(1) DEFAULT 'N' COMMENT 'KOSPI100 포함 여부',
  `is_kospi50` char(1) DEFAULT 'N' COMMENT 'KOSPI50 포함 여부',
  `is_krx` char(1) DEFAULT 'N' COMMENT 'KRX 포함 여부',
  `is_etp` char(1) DEFAULT 'N' COMMENT 'ETP 여부',
  `is_elw_issuer` char(1) DEFAULT 'N' COMMENT 'ELW 발행 여부',
  `is_krx100` char(1) DEFAULT 'N' COMMENT 'KRX100 포함 여부',
  `is_krx_automobile` char(1) DEFAULT 'N' COMMENT 'KRX 자동차 섹터',
  `is_krx_semiconductor` char(1) DEFAULT 'N' COMMENT 'KRX 반도체 섹터',
  `is_krx_bio` char(1) DEFAULT 'N' COMMENT 'KRX 바이오 섹터',
  `is_krx_bank` char(1) DEFAULT 'N' COMMENT 'KRX 은행 섹터',
  `is_spac` char(1) DEFAULT 'N' COMMENT 'SPAC 여부',
  `is_krx_energy_chemical` char(1) DEFAULT 'N' COMMENT 'KRX 에너지화학 섹터',
  `is_krx_steel` char(1) DEFAULT 'N' COMMENT 'KRX 철강 섹터',
  `is_short_term_overheated` char(1) DEFAULT 'N' COMMENT '단기과열 여부',
  `is_krx_media_telecom` char(1) DEFAULT 'N' COMMENT 'KRX 미디어통신 섹터',
  `is_krx_construction` char(1) DEFAULT 'N' COMMENT 'KRX 건설 섹터',
  `is_non1` char(1) DEFAULT 'N' COMMENT 'Non1 여부',
  `is_krx_securities` char(1) DEFAULT 'N' COMMENT 'KRX 증권 섹터',
  `is_krx_shipbuilding` char(1) DEFAULT 'N' COMMENT 'KRX 선박 섹터',
  `is_krx_insurance` char(1) DEFAULT 'N' COMMENT 'KRX 보험 섹터',
  `is_krx_transportation` char(1) DEFAULT 'N' COMMENT 'KRX 운송 섹터',
  `is_sri` char(1) DEFAULT 'N' COMMENT 'SRI(사회책임투자) 종목',
  `base_price` decimal(10,2) DEFAULT NULL COMMENT '기준가',
  `trading_unit` int(11) DEFAULT NULL COMMENT '매매수량 단위',
  `after_hours_trading_unit` int(11) DEFAULT NULL COMMENT '시간외 수량 단위',
  `is_trading_suspended` char(1) DEFAULT 'N' COMMENT '거래정지 여부',
  `is_delisting_trade` char(1) DEFAULT 'N' COMMENT '정리매매 여부',
  `is_administrative_issue` char(1) DEFAULT 'N' COMMENT '관리종목 여부',
  `market_warning_level` int(11) DEFAULT 0 COMMENT '시장경고 수준',
  `is_warning_notice` char(1) DEFAULT 'N' COMMENT '경고예고 여부',
  `is_unfaithful_disclosure` char(1) DEFAULT 'N' COMMENT '불성실공시 여부',
  `is_backdoor_listing` char(1) DEFAULT 'N' COMMENT '우회상장 여부',
  `lock_type` int(11) DEFAULT 0 COMMENT '락(Lock) 구분',
  `par_value_change` int(11) DEFAULT 0 COMMENT '액면변경 구분',
  `capital_increase_type` int(11) DEFAULT 0 COMMENT '증자 구분',
  `margin_rate` int(11) DEFAULT NULL COMMENT '증거금 비율(%)',
  `is_margin_trading_eligible` char(1) DEFAULT 'N' COMMENT '신용거래 가능 여부',
  `margin_trading_period` int(11) DEFAULT NULL COMMENT '신용거래 기간(일)',
  `previous_day_volume` bigint(20) DEFAULT NULL COMMENT '전일 거래량',
  `par_value` int(11) DEFAULT NULL COMMENT '액면가',
  `listing_date` varchar(8) DEFAULT NULL COMMENT '상장일자',
  `listed_shares` bigint(20) DEFAULT NULL COMMENT '상장주수',
  `capital_amount` bigint(20) DEFAULT NULL COMMENT '자본금',
  `fiscal_month` int(11) DEFAULT NULL COMMENT '결산월',
  `ipo_price` int(11) DEFAULT NULL COMMENT '공모가',
  `is_preferred_stock` char(1) DEFAULT 'N' COMMENT '우선주 여부',
  `is_short_selling_overheated` char(1) DEFAULT 'N' COMMENT '공매도 과열 여부',
  `is_abnormal_surge` char(1) DEFAULT 'N' COMMENT '이상급등 여부',
  `is_krx300` char(1) DEFAULT 'N' COMMENT 'KRX300 포함 여부',
  `is_kospi` char(1) DEFAULT 'N' COMMENT 'KOSPI 포함 여부',
  `revenue` bigint(20) DEFAULT NULL COMMENT '매출액',
  `operating_profit` bigint(20) DEFAULT NULL COMMENT '영업이익',
  `ordinary_income` bigint(20) DEFAULT NULL COMMENT '경상이익',
  `net_income` bigint(20) DEFAULT NULL COMMENT '당기순이익',
  `roe` decimal(5,2) DEFAULT NULL COMMENT 'ROE (자기자본수익률 %)',
  `financial_base_date` varchar(6) DEFAULT NULL COMMENT '재무정보 기준년월',
  `market_capitalization` bigint(20) DEFAULT NULL COMMENT '시가총액',
  `group_company_code` varchar(20) DEFAULT NULL COMMENT '그룹사 코드',
  `is_credit_limit_exceeded` char(1) DEFAULT 'N' COMMENT '회사신용한도 초과 여부',
  `is_collateral_loan_eligible` char(1) DEFAULT 'N' COMMENT '담보대출 가능 여부',
  `is_stock_lending_eligible` char(1) DEFAULT 'N' COMMENT '대주 가능 여부',
  `created_at` timestamp NULL DEFAULT current_timestamp() COMMENT '생성일시',
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '수정일시',
  PRIMARY KEY (`standard_code`),
  KEY `idx_short_code` (`short_code`),
  KEY `idx_korean_name` (`korean_name`),
  KEY `idx_listing_date` (`listing_date`),
  KEY `idx_market_cap` (`market_capitalization`),
  KEY `idx_group_code` (`group_code`),
  KEY `idx_kospi100` (`is_kospi100`),
  KEY `idx_kospi50` (`is_kospi50`),
  KEY `idx_krx100` (`is_krx100`),
  KEY `idx_trading_status` (`is_trading_suspended`,`is_delisting_trade`,`is_administrative_issue`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='한국 주식시장 종목 정보 및 거래 관련 데이터를 저장하는 테이블'

