spring:
  application:
    name: batch-collector
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/stock
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.mariadb.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

# KIS API 설정
kis:
  api:
    base-url: ${KIS_API_BASE_URL:https://openapivts.koreainvestment.com:29443}
    app-key: ${KIS_API_APP_KEY:test-app-key}
    app-secret: ${KIS_API_APP_SECRET:test-app-secret}
    environment: ${KIS_ENVIRONMENT:mock}
    rate-limit:
      requests-per-minute: ${KIS_RATE_LIMIT_PER_MIN:20}
      requests-per-day: ${KIS_RATE_LIMIT_PER_DAY:10000}
      max-concurrent-connections: ${KIS_MAX_CONNECTIONS:5}
    timeout:
      connection-timeout-ms: ${KIS_CONNECTION_TIMEOUT:5000}
      read-timeout-ms: ${KIS_READ_TIMEOUT:30000}
      write-timeout-ms: ${KIS_WRITE_TIMEOUT:30000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      show-details: when-authorized
    loggers:
      enabled: true

logging:
  level:
    com.stock: DEBUG
    org.springframework.batch: INFO
    org.springframework.web.reactive: DEBUG
    reactor.netty: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"