spring:
  application:
    name: api-server
  
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/stock_db
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
  
# webflux:
#   base-path: /api/v1

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

kis:
  api:
    base-url: ${KIS_API_BASE_URL:https://openapivts.koreainvestment.com:29443}
    app-key: ${KIS_API_APP_KEY:test-app-key}
    app-secret: ${KIS_API_APP_SECRET:test-app-secret}
    timeout:
      connection-timeout-ms: 5000
      read-timeout-ms: 30000
      write-timeout-ms: 30000

logging:
  level:
    com.stock: DEBUG
    org.springframework.web: INFO
    reactor.netty: INFO